version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "80:8000"
  pg:
    image: postgres:10
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

volumes:
  pgdata: